project:
  type: website
  output-dir: docs

website:
  title: "Mariana's Web Page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: project.qmd
        text: Project 1
      - href: Project_2/Final_qmd/Final.qmd
        text: Project 2
      
    tools:
      - icon: trash
        href: https://www.mountainproject.com/area/112001458/the-dump
      - icon: twitter
        href: https://x.com
      - icon: linkedin
        href: https://www.linkedin.com/in/mariana-solanilla-116bba1ab/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/solanillam/solanillam
          - text: Report a Bug
            href: https://support.github.com/
format:
  html:
    theme: lumen  # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

